# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('auto_id', models.AutoField(default=0, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Category')),
                ('subCategory', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product subCategory')),
                ('type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Type')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='Product Price')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Product Brand')),
                ('listPrice', models.BigIntegerField(blank=True, null=True, verbose_name='Product List Price')),
                ('discount', models.CharField(blank=True, max_length=10, null=True, verbose_name='Discount')),
                ('name', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Product Name')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product URL')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('availability', models.CharField(blank=True, max_length=50, null=True, verbose_name='Availability')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Colour')),
                ('productRating', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Rating')),
                ('numberRating', models.BigIntegerField(blank=True, null=True, verbose_name='Rating of the Product')),
                ('imageLink', models.CharField(blank=True, max_length=1000, verbose_name='Link of Image')),
                ('androidLink', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Android Link')),
                ('referredFrom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link From Website')),
            ],
        ),
    ]
